/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/


  insert into [Cards] values
  ('Огнегривый','/images/cards/11-001.jpg',1,1,'plains','ordinary','common','legendsSet')
,('Страж Тоа-Дана','/images/cards/11-002.jpg',2,1,'plains','ordinary','common','legendsSet')
,('Лучник Дзара','/images/cards/11-003.jpg',3,1,'plains','elite','common','legendsSet')
,('Орк-стрелок','/images/cards/11-004.jpg',4,1,'plains','elite','common','legendsSet')
,('Орк-задира','/images/cards/11-005.jpg',5,1,'plains','elite','common','legendsSet')
,('Гном-лучник','/images/cards/11-006.jpg',6,1,'mountains','ordinary','common','legendsSet')
,('Грозовой маг','/images/cards/11-007.jpg',7,1,'mountains','ordinary','common','legendsSet')
,('Железный голем','/images/cards/11-008.jpg',8,1,'mountains','ordinary','common','legendsSet')
,('Дитя вьюги','/images/cards/11-009.jpg',9,2,'mountains','ordinary','common','legendsSet')
,('Цвар','/images/cards/11-010.jpg',10,1,'mountains','elite','common','legendsSet')
,('Торговка элексирами','/images/cards/11-011.jpg',11,1,'forests','ordinary','common','legendsSet')
,('Элфийский следопыт','/images/cards/11-012.jpg',12,1,'forests','ordinary','common','legendsSet')
,('Боров Лихолесья','/images/cards/11-013.jpg',13,1,'forests','ordinary','common','legendsSet')
,('Ольгерд','/images/cards/11-014.jpg',14,1,'forests','elite','common','legendsSet')
,('Большой кулак','/images/cards/11-015.jpg',15,1,'swamps','ordinary','common','legendsSet')
,('Карга','/images/cards/11-016.jpg',16,1,'swamps','elite','common','legendsSet')
,('Раб клинка','/images/cards/11-017.jpg',17,1,'swamps','elite','common','legendsSet')
,('Тролль-воин','/images/cards/11-018.jpg',18,1,'swamps','elite','common','legendsSet')
,('Летописец','/images/cards/11-019.jpg',19,1,'neutral','ordinary','common','legendsSet')
,('Кочевник','/images/cards/01-001.jpg',1,3,'plains','ordinary','common','warSet')
,('Кшар','/images/cards/01-002.jpg',2,3,'plains','ordinary','common','warSet')
,('Волхв','/images/cards/01-003.jpg',3,3,'plains','ordinary','common','warSet')
,('Гиррит','/images/cards/01-004.jpg',4,0,'plains','ordinary','rare','warSet')
,('Ост','/images/cards/01-005.jpg',5,3,'plains','ordinary','common','warSet')
,('Пустотник','/images/cards/01-006.jpg',6,3,'plains','ordinary','common','warSet')
,('Смотритель стойла','/images/cards/01-007.jpg',7,3,'plains','ordinary','uncommon','warSet')
,('Степной волколак','/images/cards/01-008.jpg',8,3,'plains','ordinary','uncommon','warSet')
,('Хозяйка прайда','/images/cards/01-009.jpg',9,3,'plains','ordinary','common','warSet')
,('Аколит Дзара','/images/cards/01-010.jpg',10,3,'plains','ordinary','common','warSet')
,('Змееглав','/images/cards/01-011.jpg',11,3,'plains','ordinary','common','warSet')
,('Кабаний наездник','/images/cards/01-012.jpg',12,3,'plains','ordinary','uncommon','warSet')
,('Орк','/images/cards/01-013.jpg',13,3,'plains','ordinary','common','warSet')
,('Пустынный кондор','/images/cards/01-014.jpg',14,3,'plains','ordinary','uncommon','warSet')
,('Рубаки Холверта','/images/cards/01-015.jpg',15,3,'plains','ordinary','uncommon','warSet')
,('Санкторум','/images/cards/01-016.jpg',16,3,'plains','ordinary','common','warSet')
,('Арбалетчик','/images/cards/01-017.jpg',17,3,'plains','ordinary','common','warSet')
,('Килсус','/images/cards/01-018.jpg',18,3,'plains','ordinary','uncommon','warSet')
,('Щитоносец','/images/cards/01-019.jpg',19,3,'plains','ordinary','uncommon','warSet')
,('Глорм','/images/cards/01-020.jpg',20,3,'plains','elite','common','warSet')
,('Мантикора','/images/cards/01-021.jpg',21,3,'plains','elite','uncommon','warSet')
,('Орк-бомбардир','/images/cards/01-022.jpg',22,3,'plains','elite','common','warSet')
,('Риала','/images/cards/01-023.jpg',23,3,'plains','elite','common','warSet')
,('Посвящённый Дзара','/images/cards/01-024.jpg',24,3,'plains','elite','common','warSet')
,('Хронос','/images/cards/01-025.jpg',25,1,'plains','elite','rare','warSet')
,('Анубисар','/images/cards/01-026.jpg',26,2,'plains','elite','rare','warSet')
,('Бон и Берроу','/images/cards/01-027.jpg',27,2,'plains','elite','rare','warSet')
,('Матриарх племени','/images/cards/01-028.jpg',28,0,'plains','elite','ultrarare','warSet')
,('Пеший латник','/images/cards/01-029.jpg',29,3,'plains','elite','common','warSet')
,('Бронтобей','/images/cards/01-030.jpg',30,0,'plains','elite','rare','warSet')
,('Ойуун','/images/cards/01-031.jpg',31,0,'plains','elite','ultrarare','warSet')
,('Дегаска','/images/cards/01-032.jpg',32,0,'plains','elite','ultrarare','warSet')
,('Скелос','/images/cards/01-033.jpg',33,3,'plains','elite','common','warSet')
,('Минотавр','/images/cards/01-034.jpg',34,1,'plains','elite','rare','warSet')
,('Гном-поджигатель','/images/cards/01-035.jpg',35,3,'mountains','ordinary','common','warSet')
,('Ледяной змей','/images/cards/01-036.jpg',36,2,'mountains','ordinary','common','warSet')
,('Овражный гном','/images/cards/01-037.jpg',37,3,'mountains','ordinary','common','warSet')
,('Бешеный маг','/images/cards/01-038.jpg',38,3,'mountains','ordinary','common','warSet')
,('Гуль','/images/cards/01-039.jpg',39,3,'mountains','ordinary','common','warSet')
,('Мразень','/images/cards/01-040.jpg',40,3,'mountains','ordinary','common','warSet')
,('Айрин','/images/cards/01-041.jpg',41,3,'mountains','ordinary','common','warSet')
,('Знахарь племени','/images/cards/01-042.jpg',42,3,'mountains','ordinary','common','warSet')
,('Каменный голем','/images/cards/01-043.jpg',43,3,'mountains','ordinary','uncommon','warSet')
,('Страж чертогов','/images/cards/01-044.jpg',44,3,'mountains','ordinary','common','warSet')
,('Ледовый охотник','/images/cards/01-045.jpg',45,3,'mountains','ordinary','common','warSet')
,('Мастер топора','/images/cards/01-046.jpg',46,3,'mountains','ordinary','common','warSet')
,('Ртунх','/images/cards/01-047.jpg',47,3,'mountains','ordinary','common','warSet')
,('Смотритель горнила','/images/cards/01-048.jpg',48,3,'mountains','ordinary','common','warSet')
,('Центурион','/images/cards/01-049.jpg',49,3,'mountains','ordinary','uncommon','warSet')
,('Хранитель гор','/images/cards/01-050.jpg',50,3,'mountains','ordinary','common','warSet')
,('Призывающая бурю','/images/cards/01-051.jpg',51,3,'mountains','ordinary','uncommon','warSet')
,('Тан Ханеранга','/images/cards/01-052.jpg',52,3,'mountains','ordinary','uncommon','warSet')
,('Гном-басаарг','/images/cards/01-053.jpg',53,3,'mountains','ordinary','uncommon','warSet')
,('Искатель тайн','/images/cards/01-054.jpg',54,3,'mountains','elite','uncommon','warSet')
,('Борг','/images/cards/01-055.jpg',55,3,'mountains','elite','uncommon','warSet')
,('Ном','/images/cards/01-056.jpg',56,1,'mountains','elite','rare','warSet')
,('Криомант','/images/cards/01-057.jpg',57,0,'mountains','elite','rare','warSet')
,('Молотобоец','/images/cards/01-058.jpg',58,3,'mountains','elite','common','warSet')
,('Оборотень','/images/cards/01-059.jpg',59,1,'mountains','elite','rare','warSet')
,('Аргвальд','/images/cards/01-060.jpg',60,1,'mountains','elite','rare','warSet')
,('Горный великан','/images/cards/01-061.jpg',61,3,'mountains','elite','common','warSet')
,('Костедробитель','/images/cards/01-062.jpg',62,3,'mountains','elite','common','warSet')
,('Рагнар','/images/cards/01-063.jpg',63,1,'mountains','elite','rare','warSet')
,('Гобрах','/images/cards/01-064.jpg',64,3,'mountains','elite','uncommon','warSet')
,('Ледовый страж','/images/cards/01-065.jpg',65,1,'mountains','elite','ultrarare','warSet')
,('Повелитель молний','/images/cards/01-066.jpg',66,1,'mountains','elite','rare','warSet')
,('Гномий король','/images/cards/01-067.jpg',67,0,'mountains','elite','ultrarare','warSet')
,('Владыка небес','/images/cards/01-068.jpg',68,0,'mountains','elite','ultrarare','warSet')
,('Атекар','/images/cards/01-069.jpg',69,3,'forests','ordinary','common','warSet')
,('Дракс','/images/cards/01-070.jpg',70,3,'forests','ordinary','common','warSet')
,('Леший','/images/cards/01-071.jpg',71,3,'forests','ordinary','common','warSet')
,('Фея леса','/images/cards/01-072.jpg',72,3,'forests','ordinary','common','warSet')
,('Друид','/images/cards/01-073.jpg',73,3,'forests','ordinary','common','warSet')
,('Корпит','/images/cards/01-074.jpg',74,3,'forests','ordinary','common','warSet')
,('Лесной разбойник','/images/cards/01-075.jpg',75,3,'forests','ordinary','common','warSet')
,('Оури','/images/cards/01-076.jpg',76,3,'forests','ordinary','common','warSet')
,('Паук-пересмешник','/images/cards/01-077.jpg',77,3,'forests','ordinary','common','warSet')
,('Эриала','/images/cards/01-078.jpg',78,3,'forests','ordinary','uncommon','warSet')
,('Бегущая по кронам','/images/cards/01-079.jpg',79,3,'forests','ordinary','uncommon','warSet')
,('Бьёрн','/images/cards/01-080.jpg',80,3,'forests','ordinary','common','warSet')
,('Вожак сатиров','/images/cards/01-081.jpg',81,3,'forests','ordinary','uncommon','warSet')
,('Клаэр','/images/cards/01-082.jpg',82,3,'forests','ordinary','common','warSet')
,('Серк','/images/cards/01-083.jpg',83,3,'forests','ordinary','common','warSet')
,('Камнедрев','/images/cards/01-084.jpg',84,3,'forests','ordinary','common','warSet')
,('Лёккен','/images/cards/01-085.jpg',85,3,'forests','ordinary','uncommon','warSet')
,('Мира','/images/cards/01-086.jpg',86,4,'forests','ordinary','rare','warSet')
,('Фагор','/images/cards/01-087.jpg',87,3,'forests','ordinary','uncommon','warSet')
,('Резчик идолов','/images/cards/01-088.jpg',88,3,'forests','elite','common','warSet')
,('Грызь','/images/cards/01-089.jpg',89,3,'forests','elite','uncommon','warSet')
,('Дверг','/images/cards/01-090.jpg',90,0,'forests','elite','ultrarare','warSet')
,('Дикий целитель','/images/cards/01-091.jpg',91,3,'forests','elite','uncommon','warSet')
,('Кобольд','/images/cards/01-092.jpg',92,3,'forests','elite','common','warSet')
,('Очи Кронга','/images/cards/01-093.jpg',93,0,'forests','elite','ultrarare','warSet')
,('Король-жрец','/images/cards/01-094.jpg',94,0,'forests','elite','rare','warSet')
,('Ловец душ','/images/cards/01-095.jpg',95,3,'forests','elite','uncommon','warSet')
,('Тергала','/images/cards/01-096.jpg',96,0,'forests','elite','rare','warSet')
,('Эльфийский воин','/images/cards/01-097.jpg',97,3,'forests','elite','common','warSet')
,('Ётун','/images/cards/01-098.jpg',98,0,'forests','elite','rare','warSet')
,('Серый альв','/images/cards/01-099.jpg',99,0,'forests','elite','rare','warSet')
,('Хобгоблин','/images/cards/01-100.jpg',100,3,'forests','elite','common','warSet')
,('Циклоп','/images/cards/01-101.jpg',101,1,'forests','elite','rare','warSet')
,('Келе','/images/cards/01-102.jpg',102,0,'forests','elite','ultrarare','warSet')
,('Ижор','/images/cards/01-103.jpg',103,3,'swamps','ordinary','common','warSet')
,('Махинатор','/images/cards/01-104.jpg',104,3,'swamps','ordinary','common','warSet')
,('Отряд карателей','/images/cards/01-105.jpg',105,3,'swamps','ordinary','common','warSet')
,('Римаанды','/images/cards/01-106.jpg',106,3,'swamps','ordinary','common','warSet')
,('Болотник','/images/cards/01-107.jpg',107,3,'swamps','ordinary','common','warSet')
,('Дети топи','/images/cards/01-108.jpg',108,3,'swamps','ordinary','uncommon','warSet')
,('Осклизг','/images/cards/01-109.jpg',109,3,'swamps','ordinary','common','warSet')
,('Рэккен','/images/cards/01-110.jpg',110,3,'swamps','ordinary','common','warSet')
,('Тови','/images/cards/01-111.jpg',111,3,'swamps','ordinary','common','warSet')
,('Хедд','/images/cards/01-112.jpg',112,3,'swamps','ordinary','common','warSet')
,('Гаррид-лучник','/images/cards/01-113.jpg',113,3,'swamps','ordinary','common','warSet')
,('Грёзы Архааля','/images/cards/01-114.jpg',114,3,'swamps','ordinary','uncommon','warSet')
,('Кровяница','/images/cards/01-115.jpg',115,3,'swamps','ordinary','uncommon','warSet')
,('Василиск','/images/cards/01-116.jpg',116,3,'swamps','ordinary','common','warSet')
,('Вайл','/images/cards/01-117.jpg',117,3,'swamps','ordinary','common','warSet')
,('Шаман-душегрыз','/images/cards/01-118.jpg',118,1,'swamps','ordinary','rare','warSet')
,('Бул’Багур','/images/cards/01-119.jpg',119,1,'swamps','ordinary','rare','warSet')
,('Гоблин','/images/cards/01-120.jpg',120,3,'swamps','ordinary','common','warSet')
,('Слизь','/images/cards/01-121.jpg',121,3,'swamps','elite','common','warSet')
,('Дочь перламутра','/images/cards/01-122.jpg',122,3,'swamps','elite','uncommon','warSet')
,('Ноками','/images/cards/01-123.jpg',123,0,'swamps','elite','rare','warSet')
,('Сеятель хвори','/images/cards/01-124.jpg',124,3,'swamps','elite','uncommon','warSet')
,('Троллок','/images/cards/01-125.jpg',125,3,'swamps','elite','uncommon','warSet')
,('Вилохвост','/images/cards/01-126.jpg',126,3,'swamps','elite','uncommon','warSet')
,('Исхарская ненасыть','/images/cards/01-127.jpg',127,3,'swamps','elite','common','warSet')
,('Тролль','/images/cards/01-128.jpg',128,3,'swamps','elite','common','warSet')
,('Ундина','/images/cards/01-129.jpg',129,1,'swamps','elite','ultrarare','warSet')
,('Королева топи','/images/cards/01-130.jpg',130,2,'swamps','elite','ultrarare','warSet')
,('Медуза Горгона','/images/cards/01-131.jpg',131,3,'swamps','elite','common','warSet')
,('Двухголовый тролль','/images/cards/01-132.jpg',132,1,'swamps','elite','rare','warSet')
,('Морок','/images/cards/01-133.jpg',133,3,'swamps','elite','uncommon','warSet')
,('Уриил','/images/cards/01-134.jpg',134,1,'swamps','elite','rare','warSet')
,('Древний огр','/images/cards/01-135.jpg',135,1,'swamps','elite','rare','warSet')
,('Гидра','/images/cards/01-136.jpg',136,0,'swamps','elite','ultrarare','warSet')
,('Вестник мора','/images/cards/01-137.jpg',137,3,'dark','ordinary','common','warSet')
,('Огненный имп','/images/cards/01-138.jpg',138,3,'dark','ordinary','common','warSet')
,('Вампир','/images/cards/01-139.jpg',139,3,'dark','ordinary','common','warSet')
,('Ведьма слуа','/images/cards/01-140.jpg',140,3,'dark','ordinary','common','warSet')
,('Моровой всадник','/images/cards/01-141.jpg',141,3,'dark','ordinary','common','warSet')
,('Суккуб-истязатель','/images/cards/01-142.jpg',142,3,'dark','ordinary','common','warSet')
,('Возница','/images/cards/01-143.jpg',143,3,'dark','ordinary','common','warSet')
,('Герольд мрака','/images/cards/01-144.jpg',144,3,'dark','ordinary','uncommon','warSet')
,('Демон зависти','/images/cards/01-145.jpg',145,3,'dark','ordinary','uncommon','warSet')
,('Керсамская знать','/images/cards/01-146.jpg',146,3,'dark','ordinary','uncommon','warSet')
,('Повелитель мёртвых','/images/cards/01-147.jpg',147,3,'dark','ordinary','uncommon','warSet')
,('Сшиватель плоти','/images/cards/01-148.jpg',148,0,'dark','ordinary','rare','warSet')
,('Талион','/images/cards/01-149.jpg',149,3,'dark','ordinary','common','warSet')
,('Харон','/images/cards/01-150.jpg',150,3,'dark','ordinary','common','warSet')
,('Зомби','/images/cards/01-151.jpg',151,3,'dark','ordinary','common','warSet')
,('Пещерник','/images/cards/01-152.jpg',152,3,'dark','ordinary','common','warSet')
,('Сайкорон','/images/cards/01-153.jpg',153,3,'dark','ordinary','common','warSet')
,('Мрачная дворянка','/images/cards/01-154.jpg',154,0,'dark','ordinary','rare','warSet')
,('Рогатый демон','/images/cards/01-155.jpg',155,3,'dark','ordinary','uncommon','warSet')
,('Метаморф','/images/cards/01-156.jpg',156,3,'dark','elite','common','warSet')
,('Лунная баньши','/images/cards/01-157.jpg',157,3,'dark','elite','uncommon','warSet')
,('Уордак','/images/cards/01-158.jpg',158,3,'dark','elite','common','warSet')
,('Драккарх','/images/cards/01-159.jpg',159,3,'dark','elite','uncommon','warSet')
,('Лилит и Эйдерик','/images/cards/01-160.jpg',160,0,'dark','elite','ultrarare','warSet')
,('Скелетный червь','/images/cards/01-161.jpg',161,1,'dark','elite','rare','warSet')
,('Тварь','/images/cards/01-162.jpg',162,1,'dark','elite','rare','warSet')
,('Хозяин склепа','/images/cards/01-163.jpg',163,0,'dark','elite','rare','warSet')
,('Поганище','/images/cards/01-164.jpg',164,3,'dark','elite','common','warSet')
,('Барака','/images/cards/01-165.jpg',165,3,'dark','elite','common','warSet')
,('Вурдалак','/images/cards/01-166.jpg',166,3,'dark','elite','uncommon','warSet')
,('Мерцающий змей','/images/cards/01-167.jpg',167,0,'dark','elite','rare','warSet')
,('Повелитель бездны','/images/cards/01-168.jpg',168,3,'dark','elite','common','warSet')
,('Властелин хаоса','/images/cards/01-169.jpg',169,0,'dark','elite','ultrarare','warSet')
,('Демон жадности','/images/cards/01-170.jpg',170,0,'dark','elite','ultrarare','warSet')
,('Мародёр','/images/cards/01-171.jpg',171,3,'neutral','ordinary','common','warSet')
,('Ведающий запасами','/images/cards/01-172.jpg',172,3,'neutral','ordinary','uncommon','warSet')
,('Ведунья Ордена','/images/cards/01-173.jpg',173,3,'neutral','ordinary','common','warSet')
,('Взрывная Мэри','/images/cards/01-174.jpg',174,3,'neutral','ordinary','common','warSet')
,('Крондак','/images/cards/01-175.jpg',175,3,'neutral','ordinary','common','warSet')
,('Наёмник','/images/cards/01-176.jpg',176,0,'neutral','ordinary','ultrarare','warSet')
,('Следопыт','/images/cards/01-177.jpg',177,3,'neutral','ordinary','uncommon','warSet')
,('Алвалинд','/images/cards/01-178.jpg',178,1,'neutral','ordinary','rare','warSet')
,('Жжраг','/images/cards/01-179.jpg',179,3,'neutral','ordinary','common','warSet')
,('Линнет','/images/cards/01-180.jpg',180,0,'neutral','ordinary','ultrarare','warSet')
,('Ловец удачи','/images/cards/01-181.jpg',181,3,'neutral','ordinary','common','warSet')
,('Матросы Аделаиды','/images/cards/01-182.jpg',182,3,'neutral','ordinary','common','warSet')
,('Дозор Форрендора','/images/cards/01-183.jpg',183,3,'neutral','ordinary','uncommon','warSet')
,('Отшельница','/images/cards/01-184.jpg',184,3,'neutral','ordinary','common','warSet')
,('Шакси','/images/cards/01-185.jpg',185,0,'neutral','ordinary','rare','warSet')
,('Головорез','/images/cards/01-186.jpg',186,3,'neutral','ordinary','common','warSet')
,('Лазутчица','/images/cards/01-187.jpg',187,3,'neutral','ordinary','common','warSet')
,('Паладин Алламора','/images/cards/01-188.jpg',188,3,'neutral','ordinary','common','warSet')
,('Воин храма','/images/cards/01-189.jpg',189,3,'neutral','ordinary','common','warSet')
,('Вольный воитель','/images/cards/01-190.jpg',190,0,'neutral','elite','uncommon','warSet')
,('Ассасин','/images/cards/01-191.jpg',191,1,'neutral','elite','rare','warSet')
,('Ревнитель Сеггера','/images/cards/01-192.jpg',192,3,'neutral','elite','uncommon','warSet')
,('Арацент','/images/cards/01-193.jpg',193,3,'neutral','elite','uncommon','warSet')
,('Аристократка','/images/cards/01-194.jpg',194,3,'neutral','elite','uncommon','warSet')
,('Берсерк','/images/cards/01-195.jpg',195,1,'neutral','elite','rare','warSet')
,('Гермет','/images/cards/01-196.jpg',196,3,'neutral','elite','uncommon','warSet')
,('Эорвал','/images/cards/01-197.jpg',197,3,'neutral','elite','common','warSet')
,('Варлок','/images/cards/01-198.jpg',198,1,'neutral','elite','rare','warSet')
,('Тич','/images/cards/01-199.jpg',199,0,'neutral','elite','ultrarare','warSet')
,('Волот','/images/cards/01-200.jpg',200,0,'neutral','elite','ultrarare','warSet')
,('Заступник Ордена','/images/cards/02-001.jpg',1,3,'plains','ordinary','common','darkSet')
,('Кентавр','/images/cards/02-002.jpg',2,3,'plains','ordinary','common','darkSet')
,('Орчонок','/images/cards/02-003.jpg',3,3,'plains','ordinary','common','darkSet')
,('Разумный вихрь','/images/cards/02-004.jpg',4,3,'plains','ordinary','common','darkSet')
,('Иглохрюк','/images/cards/02-005.jpg',5,3,'plains','ordinary','common','darkSet')
,('Карлик Унд','/images/cards/02-006.jpg',6,3,'plains','ordinary','uncommon','darkSet')
,('Кешиар','/images/cards/02-007.jpg',7,3,'plains','ordinary','common','darkSet')
,('Кондор-стервятник','/images/cards/02-008.jpg',8,3,'plains','ordinary','uncommon','darkSet')
,('Лихо одноглазое','/images/cards/02-009.jpg',9,3,'plains','ordinary','uncommon','darkSet')
,('Поури','/images/cards/02-010.jpg',10,3,'plains','ordinary','common','darkSet')
,('Пустыня Дзара','/images/cards/02-011.jpg',11,0,'plains','ordinary','rare','darkSet')
,('Стражник Туллена','/images/cards/02-012.jpg',12,4,'plains','ordinary','common','darkSet')
,('Витязь Адрелиана','/images/cards/02-013.jpg',13,3,'plains','ordinary','common','darkSet')
,('Омидгал','/images/cards/02-014.jpg',14,0,'plains','ordinary','rare','darkSet')
,('Песчаный пират','/images/cards/02-015.jpg',15,3,'plains','ordinary','common','darkSet')
,('Пикинёр Альхенгарда','/images/cards/02-016.jpg',16,3,'plains','ordinary','common','darkSet')
,('Боргак','/images/cards/02-017.jpg',17,3,'plains','ordinary','common','darkSet')
,('Кулхан','/images/cards/02-018.jpg',18,3,'plains','ordinary','common','darkSet')
,('Ясновидящая','/images/cards/02-019.jpg',19,3,'plains','ordinary','uncommon','darkSet')
,('Раптор','/images/cards/02-020.jpg',20,0,'plains','ordinary','ultrarare','darkSet')
,('Купец','/images/cards/02-021.jpg',21,3,'plains','elite','common','darkSet')
,('Стратег','/images/cards/02-022.jpg',22,3,'plains','elite','uncommon','darkSet')
,('Сфинкс Дзара','/images/cards/02-023.jpg',23,3,'plains','elite','uncommon','darkSet')
,('Великая катапульта','/images/cards/02-024.jpg',24,1,'plains','elite','rare','darkSet')
,('Джилла','/images/cards/02-025.jpg',25,0,'plains','elite','rare','darkSet')
,('Маг Тор-Гарона','/images/cards/02-026.jpg',26,0,'plains','elite','rare','darkSet')
,('Пиромант Дзара','/images/cards/02-027.jpg',27,3,'plains','elite','common','darkSet')
,('Степной варвар','/images/cards/02-028.jpg',28,3,'plains','elite','common','darkSet')
,('Орк-арбалетчик','/images/cards/02-029.jpg',29,3,'plains','elite','uncommon','darkSet')
,('Рыцарь Туллена','/images/cards/02-030.jpg',30,0,'plains','elite','rare','darkSet')
,('Хазг','/images/cards/02-031.jpg',31,3,'plains','elite','uncommon','darkSet')
,('Адрелиан','/images/cards/02-032.jpg',32,0,'plains','elite','ultrarare','darkSet')
,('Кест','/images/cards/02-033.jpg',33,3,'plains','elite','common','darkSet')
,('Свирепый Резак','/images/cards/02-034.jpg',34,0,'plains','elite','ultrarare','darkSet')
,('Гном-арбалетчик','/images/cards/02-035.jpg',35,5,'mountains','ordinary','common','darkSet')
,('Лучница Снорганга','/images/cards/02-036.jpg',36,3,'mountains','ordinary','common','darkSet')
,('Стражница Ульфгарда','/images/cards/02-037.jpg',37,3,'mountains','ordinary','common','darkSet')
,('Гарпунщик','/images/cards/02-038.jpg',38,3,'mountains','ordinary','common','darkSet')
,('Дух горы','/images/cards/02-039.jpg',39,3,'mountains','ordinary','common','darkSet')
,('Жрец штормов','/images/cards/02-040.jpg',40,3,'mountains','ordinary','uncommon','darkSet')
,('Ратник Крейд-Моора','/images/cards/02-041.jpg',41,3,'mountains','ordinary','common','darkSet')
,('Скальд','/images/cards/02-042.jpg',42,3,'mountains','ordinary','common','darkSet')
,('Скальный фантом','/images/cards/02-043.jpg',43,3,'mountains','ordinary','common','darkSet')
,('Альгорн','/images/cards/02-044.jpg',44,3,'mountains','ordinary','common','darkSet')
,('Астральный двойник','/images/cards/02-045.jpg',45,3,'mountains','ordinary','uncommon','darkSet')
,('Гаргулья','/images/cards/02-046.jpg',46,3,'mountains','ordinary','common','darkSet')
,('Ледяной тролль','/images/cards/02-047.jpg',47,3,'mountains','ordinary','uncommon','darkSet')
,('Олаф','/images/cards/02-048.jpg',48,3,'mountains','ordinary','common','darkSet')
,('Сердце бурь','/images/cards/02-049.jpg',49,0,'mountains','ordinary','rare','darkSet')
,('Сигурд','/images/cards/02-050.jpg',50,3,'mountains','ordinary','common','darkSet')
,('Черновар','/images/cards/02-051.jpg',51,3,'mountains','ordinary','uncommon','darkSet')
,('Хозяйка лавин','/images/cards/02-052.jpg',52,3,'mountains','ordinary','uncommon','darkSet')
,('Прорицательница вершин','/images/cards/02-053.jpg',53,0,'mountains','ordinary','ultrarare','darkSet')
,('Раннан','/images/cards/02-054.jpg',54,0,'mountains','ordinary','rare','darkSet')
,('Скалы Лант-Мора','/images/cards/02-055.jpg',55,0,'mountains','elite','rare','darkSet')
,('Шипокрыл','/images/cards/02-056.jpg',56,3,'mountains','elite','common','darkSet')
,('Валькирия','/images/cards/02-057.jpg',57,0,'mountains','elite','ultrarare','darkSet')
,('Глиняный голем','/images/cards/02-058.jpg',58,3,'mountains','elite','common','darkSet')
,('Камень гнева','/images/cards/02-059.jpg',59,3,'mountains','elite','uncommon','darkSet')
,('Кугхор','/images/cards/02-060.jpg',60,3,'mountains','elite','common','darkSet')
,('Дхайа','/images/cards/02-061.jpg',61,3,'mountains','elite','uncommon','darkSet')
,('Морозный тюремщик','/images/cards/02-062.jpg',62,0,'mountains','elite','rare','darkSet')
,('Нага','/images/cards/02-063.jpg',63,3,'mountains','elite','common','darkSet')
,('Гаргант','/images/cards/02-064.jpg',64,3,'mountains','elite','common','darkSet')
,('Торбьёрн','/images/cards/02-065.jpg',65,3,'mountains','elite','uncommon','darkSet')
,('Хельмир','/images/cards/02-066.jpg',66,1,'mountains','elite','rare','darkSet')
,('Фенрир','/images/cards/02-067.jpg',67,0,'mountains','elite','ultrarare','darkSet')
,('Рукан','/images/cards/02-068.jpg',68,0,'mountains','elite','rare','darkSet')
,('Эльм','/images/cards/02-069.jpg',69,3,'forests','ordinary','common','darkSet')
,('Бяка','/images/cards/02-070.jpg',70,3,'forests','ordinary','common','darkSet')
,('Лепрекон','/images/cards/02-071.jpg',71,3,'forests','ordinary','common','darkSet')
,('Вепрь Святолесья','/images/cards/02-072.jpg',72,2,'forests','ordinary','uncommon','darkSet')
,('Гигантский орёл','/images/cards/02-073.jpg',73,3,'forests','ordinary','common','darkSet')
,('Разведчик эльфов','/images/cards/02-074.jpg',74,3,'forests','ordinary','uncommon','darkSet')
,('Раэннат','/images/cards/02-075.jpg',75,1,'forests','ordinary','rare','darkSet')
,('Рейнджер','/images/cards/02-076.jpg',76,3,'forests','ordinary','common','darkSet')
,('Санитар рощи','/images/cards/02-077.jpg',77,3,'forests','ordinary','common','darkSet')
,('Ламия','/images/cards/02-078.jpg',78,0,'forests','ordinary','rare','darkSet')
,('Мара','/images/cards/02-079.jpg',79,3,'forests','ordinary','uncommon','darkSet')
,('Пастух Кронга','/images/cards/02-080.jpg',80,3,'forests','ordinary','common','darkSet')
,('Ягуар','/images/cards/02-081.jpg',81,3,'forests','ordinary','common','darkSet')
,('Борсан','/images/cards/02-082.jpg',82,0,'forests','ordinary','ultrarare','darkSet')
,('Гвеор','/images/cards/02-083.jpg',83,3,'forests','ordinary','common','darkSet')
,('Грост','/images/cards/02-084.jpg',84,3,'forests','ordinary','uncommon','darkSet')
,('Жрица Алламора','/images/cards/02-085.jpg',85,3,'forests','ordinary','common','darkSet')
,('Рузарх','/images/cards/02-086.jpg',86,3,'forests','ordinary','common','darkSet')
,('Гризли Кронга','/images/cards/02-087.jpg',87,3,'forests','ordinary','uncommon','darkSet')
,('Часовые Кронга','/images/cards/02-088.jpg',88,0,'forests','ordinary','rare','darkSet')
,('Бурый волк','/images/cards/02-089.jpg',89,3,'forests','elite','common','darkSet')
,('Гмурр','/images/cards/02-090.jpg',90,3,'forests','elite','common','darkSet')
,('Эльф-задира','/images/cards/02-091.jpg',91,3,'forests','elite','common','darkSet')
,('Бард Святолесья','/images/cards/02-092.jpg',92,3,'forests','elite','uncommon','darkSet')
,('Орк-птицелов','/images/cards/02-093.jpg',93,3,'forests','elite','common','darkSet')
,('Хрумг','/images/cards/02-094.jpg',94,3,'forests','elite','uncommon','darkSet')
,('Чародейка','/images/cards/02-095.jpg',95,3,'forests','elite','uncommon','darkSet')
,('Эльфийский арсенал','/images/cards/02-096.jpg',96,0,'forests','elite','rare','darkSet')
,('Вейде','/images/cards/02-097.jpg',97,0,'forests','elite','ultrarare','darkSet')
,('Тхель-Вэнн','/images/cards/02-098.jpg',98,0,'forests','elite','ultrarare','darkSet')
,('Дикий циклоп','/images/cards/02-099.jpg',99,0,'forests','elite','rare','darkSet')
,('Исса','/images/cards/02-100.jpg',100,3,'forests','elite','common','darkSet')
,('Единорог','/images/cards/02-101.jpg',101,1,'forests','elite','rare','darkSet')
,('Линдвурм','/images/cards/02-102.jpg',102,3,'forests','elite','common','darkSet')
,('Невеста окуня','/images/cards/02-103.jpg',103,3,'swamps','ordinary','common','darkSet')
,('Нервный ург','/images/cards/02-104.jpg',104,3,'swamps','ordinary','common','darkSet')
,('Виверна','/images/cards/02-105.jpg',105,3,'swamps','ordinary','common','darkSet')
,('Дымный Ууг','/images/cards/02-106.jpg',106,3,'swamps','ordinary','common','darkSet')
,('Зендар','/images/cards/02-107.jpg',107,3,'swamps','ordinary','common','darkSet')
,('Призрак Зенды','/images/cards/02-108.jpg',108,3,'swamps','ordinary','uncommon','darkSet')
,('Руины Уорлога','/images/cards/02-109.jpg',109,0,'swamps','ordinary','rare','darkSet')
,('Топи Зенды','/images/cards/02-110.jpg',110,0,'swamps','ordinary','rare','darkSet')
,('Торфяной змей','/images/cards/02-111.jpg',111,3,'swamps','ordinary','common','darkSet')
,('Умпи','/images/cards/02-112.jpg',112,3,'swamps','ordinary','common','darkSet')
,('Шутовка','/images/cards/02-113.jpg',113,3,'swamps','ordinary','common','darkSet')
,('Щупальце кракена','/images/cards/02-114.jpg',114,5,'swamps','ordinary','common','darkSet')
,('Ядовитый плющ','/images/cards/02-115.jpg',115,3,'swamps','ordinary','common','darkSet')
,('Ахти','/images/cards/02-116.jpg',116,3,'swamps','ordinary','common','darkSet')
,('Джаал','/images/cards/02-117.jpg',117,3,'swamps','ordinary','common','darkSet')
,('Обелиск топей','/images/cards/02-118.jpg',118,3,'swamps','ordinary','uncommon','darkSet')
,('Тифозный вайл','/images/cards/02-119.jpg',119,3,'swamps','ordinary','uncommon','darkSet')
,('Хэсодэ','/images/cards/02-120.jpg',120,0,'swamps','ordinary','ultrarare','darkSet')
,('Информатор','/images/cards/02-121.jpg',121,3,'swamps','ordinary','uncommon','darkSet')
,('Ррег','/images/cards/02-122.jpg',122,0,'swamps','ordinary','rare','darkSet')
,('Трясинщик','/images/cards/02-123.jpg',123,3,'swamps','elite','common','darkSet')
,('Утопец','/images/cards/02-124.jpg',124,3,'swamps','elite','common','darkSet')
,('Ведьма','/images/cards/02-125.jpg',125,0,'swamps','elite','rare','darkSet')
,('Живая стена','/images/cards/02-126.jpg',126,3,'swamps','elite','uncommon','darkSet')
,('Итинери','/images/cards/02-127.jpg',127,0,'swamps','elite','rare','darkSet')
,('Пустоголов','/images/cards/02-128.jpg',128,3,'swamps','elite','common','darkSet')
,('Слух Архааля','/images/cards/02-129.jpg',129,3,'swamps','elite','uncommon','darkSet')
,('Древняя черепаха','/images/cards/02-130.jpg',130,3,'swamps','elite','common','darkSet')
,('Иринди','/images/cards/02-131.jpg',131,3,'swamps','elite','uncommon','darkSet')
,('Кракен','/images/cards/02-132.jpg',132,0,'swamps','elite','ultrarare','darkSet')
,('Одинокий призрак','/images/cards/02-133.jpg',133,3,'swamps','elite','uncommon','darkSet')
,('Король Астейрос','/images/cards/02-134.jpg',134,0,'swamps','elite','ultrarare','darkSet')
,('Тролль-людоед','/images/cards/02-135.jpg',135,3,'swamps','elite','common','darkSet')
,('Броненосец','/images/cards/02-136.jpg',136,0,'swamps','elite','rare','darkSet')
,('Бес','/images/cards/02-137.jpg',137,5,'dark','ordinary','common','darkSet')
,('Выкормыш слуа','/images/cards/02-138.jpg',138,5,'dark','ordinary','common','darkSet')
,('Могильный жук','/images/cards/02-139.jpg',139,3,'dark','ordinary','uncommon','darkSet')
,('Саламандра','/images/cards/02-140.jpg',140,3,'dark','ordinary','uncommon','darkSet')
,('Скелет','/images/cards/02-141.jpg',141,1,'dark','ordinary','common','darkSet')
,('Малефик','/images/cards/02-142.jpg',142,3,'dark','ordinary','uncommon','darkSet')
,('Могильный демон','/images/cards/02-143.jpg',143,3,'dark','ordinary','common','darkSet')
,('Призрачный рыцарь','/images/cards/02-144.jpg',144,3,'dark','ordinary','common','darkSet')
,('Проклятый маг','/images/cards/02-145.jpg',145,3,'dark','ordinary','common','darkSet')
,('Пустошь Тул-Багар','/images/cards/02-146.jpg',146,0,'dark','ordinary','rare','darkSet')
,('Берелгал','/images/cards/02-147.jpg',147,3,'dark','ordinary','common','darkSet')
,('Демонические врата','/images/cards/02-148.jpg',148,3,'dark','ordinary','uncommon','darkSet')
,('Живущий в тумане','/images/cards/02-149.jpg',149,3,'dark','ordinary','common','darkSet')
,('Когтистый палач','/images/cards/02-150.jpg',150,3,'dark','ordinary','common','darkSet')
,('Надих','/images/cards/02-151.jpg',151,3,'dark','ordinary','common','darkSet')
,('Скелетная гончая','/images/cards/02-152.jpg',152,3,'dark','ordinary','common','darkSet')
,('Исчадие','/images/cards/02-153.jpg',153,3,'dark','ordinary','common','darkSet')
,('Проклятая мумия','/images/cards/02-154.jpg',154,3,'dark','ordinary','common','darkSet')
,('Дзингор','/images/cards/02-155.jpg',155,3,'dark','ordinary','common','darkSet')
,('Перевёртыш','/images/cards/02-156.jpg',156,0,'dark','ordinary','rare','darkSet')
,('Дракон-зомби','/images/cards/02-157.jpg',157,3,'dark','ordinary','uncommon','darkSet')
,('Кровавый оракул','/images/cards/02-158.jpg',158,3,'dark','elite','uncommon','darkSet')
,('Мертвяцкая бомбарда','/images/cards/02-159.jpg',159,3,'dark','elite','uncommon','darkSet')
,('Адепт тьмы','/images/cards/02-160.jpg',160,0,'dark','elite','rare','darkSet')
,('Всадники слуа','/images/cards/02-161.jpg',161,3,'dark','elite','common','darkSet')
,('Лаэтар','/images/cards/02-162.jpg',162,0,'dark','elite','rare','darkSet')
,('Огненный демон','/images/cards/02-163.jpg',163,3,'dark','elite','common','darkSet')
,('Королева мёртвых','/images/cards/02-164.jpg',164,0,'dark','elite','ultrarare','darkSet')
,('Тёмный эльф','/images/cards/02-165.jpg',165,3,'dark','elite','uncommon','darkSet')
,('Шарль де Лорм','/images/cards/02-166.jpg',166,0,'dark','elite','rare','darkSet')
,('Раэр','/images/cards/02-167.jpg',167,0,'dark','elite','rare','darkSet')
,('Арахнид','/images/cards/02-168.jpg',168,3,'dark','elite','common','darkSet')
,('Далукар','/images/cards/02-169.jpg',169,0,'dark','elite','ultrarare','darkSet')
,('Левиафан','/images/cards/02-170.jpg',170,0,'dark','elite','ultrarare','darkSet')
,('Ури','/images/cards/02-171.jpg',171,3,'neutral','ordinary','common','darkSet')
,('Аларино','/images/cards/02-172.jpg',172,3,'neutral','ordinary','common','darkSet')
,('Алтарь Хигарта','/images/cards/02-173.jpg',173,3,'neutral','ordinary','uncommon','darkSet')
,('Иркиан','/images/cards/02-174.jpg',174,3,'neutral','ordinary','uncommon','darkSet')
,('Йоро','/images/cards/02-175.jpg',175,0,'neutral','ordinary','rare','darkSet')
,('Охотник за головами','/images/cards/02-176.jpg',176,3,'neutral','ordinary','common','darkSet')
,('Пономарь','/images/cards/02-177.jpg',177,3,'neutral','ordinary','common','darkSet')
,('Землекоп','/images/cards/02-178.jpg',178,3,'neutral','ordinary','uncommon','darkSet')
,('Изувер','/images/cards/02-179.jpg',179,3,'neutral','ordinary','common','darkSet')
,('Картограф','/images/cards/02-180.jpg',180,3,'neutral','ordinary','uncommon','darkSet')
,('Корсар Эллиона','/images/cards/02-181.jpg',181,3,'neutral','ordinary','common','darkSet')
,('Оруженосец','/images/cards/02-182.jpg',182,3,'neutral','ordinary','common','darkSet')
,('Стерегущий добычу','/images/cards/02-183.jpg',183,3,'neutral','ordinary','common','darkSet')
,('Ведьмак','/images/cards/02-184.jpg',184,3,'neutral','ordinary','uncommon','darkSet')
,('Кьелэрн','/images/cards/02-185.jpg',185,0,'neutral','ordinary','rare','darkSet')
,('Разящий в ночи','/images/cards/02-186.jpg',186,3,'neutral','ordinary','common','darkSet')
,('Рекрутер Храма','/images/cards/02-187.jpg',187,3,'neutral','ordinary','uncommon','darkSet')
,('Судовой кок','/images/cards/02-188.jpg',188,3,'neutral','ordinary','common','darkSet')
,('Тайник Эллиона','/images/cards/02-189.jpg',189,3,'neutral','ordinary','common','darkSet')
,('Крестоносец Сеггера','/images/cards/02-190.jpg',190,3,'neutral','ordinary','common','darkSet')
,('Гном-отступник','/images/cards/02-191.jpg',191,3,'neutral','elite','uncommon','darkSet')
,('Аделаида','/images/cards/02-192.jpg',192,0,'neutral','elite','rare','darkSet')
,('Алетрис','/images/cards/02-193.jpg',193,0,'neutral','elite','rare','darkSet')
,('Мастер разума','/images/cards/02-194.jpg',194,3,'neutral','elite','uncommon','darkSet')
,('Горец','/images/cards/02-195.jpg',195,0,'neutral','elite','rare','darkSet')
,('Старая гвардия','/images/cards/02-196.jpg',196,3,'neutral','elite','common','darkSet')
,('Феникс','/images/cards/02-197.jpg',197,0,'neutral','elite','rare','darkSet')
,('Хранитель Хартии','/images/cards/02-198.jpg',198,0,'neutral','elite','rare','darkSet')
,('Хигарт','/images/cards/02-199.jpg',199,0,'neutral','elite','rare','darkSet')
,('Кнеллервирм','/images/cards/02-200.jpg',200,0,'neutral','elite','ultrarare','darkSet')
