update Cards set ExpDef=1,IsDefPoison=1 where Name='Железный голем'
update Cards set IsDefShot=1 where Name='Дитя вьюги'
update Cards set ExpAtack=1,Armor=2 where Name='Цвар'
update Cards set ExpDef=1 where Name='Элфийский следопыт'
update Cards set IsDefPoison=1 where Name='Боров Лихолесья'
update Cards set IsTarget=1 where Name='Ольгерд'
update Cards set Regen=2 where Name='Большой кулак'
update Cards set ExpDef=1 where Name='Раб клинка'
update Cards set Regen=1 where Name='Тролль-воин'
update Cards set ExpAtack=1,IsDefPoison=1,Regen=1 where Name='Степной волколак'
update Cards set ExpDef=1,ExpAtack=1 where Name='Змееглав'
update Cards set ExpAtack=1 where Name='Кабаний наездник'
update Cards set ExpAtack=1 where Name='Килсус'
update Cards set ExpDef=2 where Name='Щитоносец'
update Cards set IsDefSpell=1 where Name='Мантикора'
update Cards set IsDefThrow=1 where Name='Риала'
update Cards set IsDefStrike=1 where Name='Посвящённый Дзара'
update Cards set IsDefShot=1 where Name='Хронос'
update Cards set Armor=1 where Name='Анубисар'
update Cards set ExpAtack=1,Armor=1 where Name='Бон и Берроу'
update Cards set IsDefMagic=1 where Name='Матриарх племени'
update Cards set IsDefShot=1 where Name='Пеший латник'
update Cards set ExpAtack=2,IsTarget=1 where Name='Бронтобей'
update Cards set IsDefShot=1 where Name='Ойуун'
update Cards set ExpAtack=1,IsDefSpell=1 where Name='Дегаска'
update Cards set ExpAtack=2,IsDefMagic=1 where Name='Скелос'
update Cards set Armor=2 where Name='Минотавр'
update Cards set IsTarget=1 where Name='Овражный гном'
update Cards set IsDefStrike=1 where Name='Айрин'
update Cards set Armor=1 where Name='Страж чертогов'
update Cards set Armor=1 where Name='Мастер топора'
update Cards set ExpDef=1 where Name='Ртунх'
update Cards set IsDefFly=1 where Name='Центурион'
update Cards set IsDefPoison=1 where Name='Хранитель гор'
update Cards set Armor=1 where Name='Тан Ханеранга'
update Cards set ExpAtack=1 where Name='Гном-басаарг'
update Cards set ExpDef=1,ExpAtack=1 where Name='Костедробитель'
update Cards set ExpAtack=1,IsDefThrow=1 where Name='Рагнар'
update Cards set Regen=3 where Name='Гобрах'
update Cards set IsDefPoison=1,IsDefShot=1 where Name='Ледовый страж'
update Cards set IsDefMagic=1 where Name='Повелитель молний'
update Cards set ExpAtack=1,IsDefMagic=1 where Name='Гномий король'
update Cards set IsDefSpell=1 where Name='Владыка небес'
update Cards set Regen=1 where Name='Атекар'
update Cards set IsTarget=1 where Name='Дракс'
update Cards set IsDefPoison=1 where Name='Друид'
update Cards set IsTarget=1 where Name='Корпит'
update Cards set IsDefStrike=1 where Name='Оури'
update Cards set ExpDef=1,IsDefMagic=1 where Name='Бьёрн'
update Cards set IsDefSpell=1 where Name='Вожак сатиров'
update Cards set IsDefShot=1 where Name='Клаэр'
update Cards set IsDefThrow=1 where Name='Серк'
update Cards set Regen=1 where Name='Камнедрев'
update Cards set ExpDef=1,IsDefStrike=1 where Name='Лёккен'
update Cards set IsDefShot=1,IsDefMagic=1 where Name='Грызь'
update Cards set IsDefShot=1 where Name='Кобольд'
update Cards set IsDefSpell=1,IsTarget=1 where Name='Очи Кронга'
update Cards set IsDefFly=1 where Name='Ловец душ'
update Cards set ExpAtack=1 where Name='Эльфийский воин'
update Cards set ExpAtack=1,IsDefMagic=1 where Name='Ётун'
update Cards set IsDefFly=1 where Name='Серый альв'
update Cards set IsDefPoison=1,IsTarget=1 where Name='Хобгоблин'
update Cards set IsDefPoison=1,IsDefMagic=1,IsTarget=1,Regen=1 where Name='Циклоп'
update Cards set IsDefMagic=1,Regen=2 where Name='Осклизг'
update Cards set Regen=1 where Name='Хедд'
update Cards set IsTarget=1 where Name='Василиск'
update Cards set IsDefShot=1 where Name='Шаман-душегрыз'
update Cards set IsDefPoison=1,Regen=1 where Name='Бул’Багур'
update Cards set IsTarget=1 where Name='Гоблин'
update Cards set Regen=1 where Name='Слизь'
update Cards set ExpDef=1 where Name='Дочь перламутра'
update Cards set IsDefShot=1 where Name='Ноками'
update Cards set ExpAtack=1,IsDefPoison=1 where Name='Вилохвост'
update Cards set ExpAtack=1,IsDefStrike=1 where Name='Исхарская ненасыть'
update Cards set ExpAtack=1,Regen=2 where Name='Тролль'
update Cards set IsDefPoison=1,IsDefStrike=1,IsDefThrow=1 where Name='Ундина'
update Cards set IsDefMagic=1 where Name='Королева топи'
update Cards set IsTarget=1 where Name='Медуза Горгона'
update Cards set IsDefSpell=1,Regen=1 where Name='Двухголовый тролль'
update Cards set ExpDef=1 where Name='Морок'
update Cards set Regen=1 where Name='Уриил'
update Cards set ExpAtack=1,IsDefPoison=1,Regen=1 where Name='Древний огр'
update Cards set IsDefSpell=1,Regen=1 where Name='Гидра'
update Cards set ExpDef=1 where Name='Вестник мора'
update Cards set Armor=1 where Name='Моровой всадник'
update Cards set ExpAtack=1 where Name='Возница'
update Cards set IsDefSpell=1 where Name='Герольд мрака'
update Cards set ExpAtack=1,Armor=1 where Name='Талион'
update Cards set IsTarget=1 where Name='Зомби'
update Cards set IsDefFly=1 where Name='Пещерник'
update Cards set IsDefStrike=1,Armor=1 where Name='Мрачная дворянка'
update Cards set IsDefFly=1,IsDefPoison=1,IsDefShot=1 where Name='Рогатый демон'
update Cards set IsTarget=1 where Name='Метаморф'
update Cards set IsDefMagic=1 where Name='Лунная баньши'
update Cards set ExpAtack=1 where Name='Уордак'
update Cards set IsDefPoison=1 where Name='Драккарх'
update Cards set IsDefThrow=1 where Name='Лилит и Эйдерик'
update Cards set IsDefShot=1 where Name='Тварь'
update Cards set ExpDef=1 where Name='Барака'
update Cards set ExpAtack=1 where Name='Вурдалак'
update Cards set ExpAtack=1 where Name='Мерцающий змей'
update Cards set IsDefSpell=1 where Name='Повелитель бездны'
update Cards set ExpDef=1,ExpAtack=1,IsDefShot=1,IsDefSpell=1 where Name='Властелин хаоса'
update Cards set IsDefStrike=1 where Name='Демон жадности'
update Cards set IsDefShot=1 where Name='Ведунья Ордена'
update Cards set ExpDef=1 where Name='Наёмник'
update Cards set IsTarget=1 where Name='Жжраг'
update Cards set IsDefMagic=1 where Name='Линнет'
update Cards set IsDefSpell=1 where Name='Шакси'
update Cards set IsDefShot=1 where Name='Головорез'
update Cards set IsDefThrow=1 where Name='Лазутчица'
update Cards set Armor=1 where Name='Паладин Алламора'
update Cards set ExpAtack=1,Armor=1 where Name='Вольный воитель'
update Cards set ExpAtack=1,IsDefPoison=1 where Name='Арацент'
update Cards set ExpAtack=1,IsDefPoison=1,IsDefSpell=1,IsTarget=1 where Name='Берсерк'
update Cards set ExpAtack=1,IsDefStrike=1,IsTarget=1 where Name='Тич'
update Cards set IsDefPoison=1,IsDefStrike=1 where Name='Волот'
update Cards set IsDefThrow=1 where Name='Заступник Ордена'
update Cards set ExpDef=1 where Name='Иглохрюк'
update Cards set Armor=1 where Name='Стражник Туллена'
update Cards set ExpAtack=1,Armor=1 where Name='Омидгал'
update Cards set IsDefShot=1 where Name='Песчаный пират'
update Cards set Armor=1 where Name='Пикинёр Альхенгарда'
update Cards set IsDefShot=1 where Name='Боргак'
update Cards set IsTarget=1 where Name='Кулхан'
update Cards set IsDefFly=1 where Name='Ясновидящая'
update Cards set ExpDef=1 where Name='Раптор'
update Cards set ExpAtack=1 where Name='Сфинкс Дзара'
update Cards set IsDefPoison=1 where Name='Маг Тор-Гарона'
update Cards set IsDefMagic=1 where Name='Пиромант Дзара'
update Cards set ExpAtack=1 where Name='Степной варвар'
update Cards set IsDefShot=1,Armor=3 where Name='Рыцарь Туллена'
update Cards set IsDefThrow=1 where Name='Хазг'
update Cards set ExpDef=2,Armor=1 where Name='Адрелиан'
update Cards set IsDefPoison=1 where Name='Кест'
update Cards set ExpAtack=2,Armor=1 where Name='Свирепый Резак'
update Cards set IsDefFly=1 where Name='Жрец штормов'
update Cards set Armor=1 where Name='Ратник Крейд-Моора'
update Cards set IsDefShot=1 where Name='Скальд'
update Cards set IsDefPoison=1 where Name='Гаргулья'
update Cards set IsDefPoison=1 where Name='Ледяной тролль'
update Cards set ExpDef=1,ExpAtack=1 where Name='Олаф'
update Cards set IsDefShot=1 where Name='Сигурд'
update Cards set IsDefMagic=1 where Name='Хозяйка лавин'
update Cards set IsDefMagic=1 where Name='Прорицательница вершин'
update Cards set IsDefMagic=1 where Name='Раннан'
update Cards set ExpAtack=2,IsTarget=1 where Name='Шипокрыл'
update Cards set IsDefPoison=1 where Name='Глиняный голем'
update Cards set IsDefStrike=1 where Name='Дхайа'
update Cards set IsDefThrow=1 where Name='Морозный тюремщик'
update Cards set ExpAtack=1,IsDefPoison=1 where Name='Нага'
update Cards set Armor=2 where Name='Гаргант'
update Cards set IsDefSpell=1 where Name='Хельмир'
update Cards set ExpAtack=1 where Name='Фенрир'
update Cards set IsDefShot=1 where Name='Рукан'
update Cards set IsTarget=1 where Name='Гигантский орёл'
update Cards set IsDefFly=1 where Name='Разведчик эльфов'
update Cards set ExpDef=1 where Name='Ламия'
update Cards set IsDefMagic=1 where Name='Мара'
update Cards set IsDefStrike=1 where Name='Пастух Кронга'
update Cards set IsDefShot=1 where Name='Борсан'
update Cards set IsDefSpell=1 where Name='Грост'
update Cards set Regen=1 where Name='Жрица Алламора'
update Cards set Regen=1 where Name='Рузарх'
update Cards set IsDefShot=1,IsStamina=1 where Name='Гризли Кронга'
update Cards set ExpAtack=1 where Name='Часовые Кронга'
update Cards set ExpShot=1 where Name='Гмурр'
update Cards set IsDefFly=1 where Name='Бард Святолесья'
update Cards set IsDefPoison=1 where Name='Хрумг'
update Cards set IsDefMagic=1,IsTarget=1 where Name='Вейде'
update Cards set IsDefShot=1 where Name='Тхель-Вэнн'
update Cards set Regen=1 where Name='Дикий циклоп'
update Cards set ExpDef=1,IsDefShot=1 where Name='Исса'
update Cards set IsDefMagic=1 where Name='Единорог'
update Cards set Regen=1 where Name='Линдвурм'
update Cards set Regen=1 where Name='Нервный ург'
update Cards set Regen=1 where Name='Дымный Ууг'
update Cards set ExpDef=2,IsDefPoison=1 where Name='Зендар'
update Cards set IsTarget=1 where Name='Торфяной змей'
update Cards set ExpDef=1 where Name='Умпи'
update Cards set IsHorde=1,Regen=1 where Name='Щупальце кракена'
update Cards set Regen=1 where Name='Ядовитый плющ'
update Cards set IsDefMagic=1 where Name='Ахти'
update Cards set IsDefThrow=1 where Name='Тифозный вайл'
update Cards set IsDefSpell=1 where Name='Хэсодэ'
update Cards set IsStamina=1 where Name='Информатор'
update Cards set ExpDef=1 where Name='Ррег'
update Cards set Regen=1 where Name='Утопец'
update Cards set ExpDef=1 where Name='Живая стена'
update Cards set IsDefPoison=1 where Name='Итинери'
update Cards set IsDefMagic=1 where Name='Иринди'
update Cards set IsDefPoison=1,Regen=1 where Name='Кракен'
update Cards set IsDefShot=1,Regen=2 where Name='Король Астейрос'
update Cards set Regen=1 where Name='Тролль-людоед'
update Cards set IsDefFly=1,IsDefShot=1 where Name='Броненосец'
update Cards set IsHorde=1,ExpDef=1 where Name='Бес'
update Cards set IsHorde=1,IsDefPoison=1 where Name='Скелет'
update Cards set IsDefShot=1 where Name='Когтистый палач'
update Cards set IsDefFly=1 where Name='Надих'
update Cards set ExpDef=1,IsDefMagic=1 where Name='Исчадие'
update Cards set IsDefSpell=1 where Name='Проклятая мумия'
update Cards set IsDefStrike=1 where Name='Дзингор'
update Cards set IsDefShot=1 where Name='Перевёртыш'
update Cards set IsDefThrow=1 where Name='Кровавый оракул'
update Cards set IsDefPoison=1 where Name='Адепт тьмы'
update Cards set IsStamina=1 where Name='Всадники слуа'
update Cards set IsDefPoison=1,IsDefShot=1 where Name='Огненный демон'
update Cards set IsDefMagic=1 where Name='Королева мёртвых'
update Cards set IsDefFly=1 where Name='Тёмный эльф'
update Cards set IsDefShot=1 where Name='Шарль де Лорм'
update Cards set Regen=1 where Name='Арахнид'
update Cards set IsDefSpell=1 where Name='Далукар'
update Cards set IsDefMagic=1 where Name='Левиафан'
update Cards set ExpDef=1 where Name='Ури'
update Cards set IsDefThrow=1 where Name='Аларино'
update Cards set IsDefFly=1 where Name='Картограф'
update Cards set ExpDef=1 where Name='Оруженосец'
update Cards set IsDefSpell=1 where Name='Ведьмак'
update Cards set IsDefShot=1 where Name='Кьелэрн'
update Cards set ExpDef=1 where Name='Судовой кок'
update Cards set Armor=1 where Name='Крестоносец Сеггера'
update Cards set IsDefShot=1 where Name='Гном-отступник'
update Cards set IsDefMagic=1 where Name='Аделаида'
update Cards set IsDefShot=1,IsTarget=1 where Name='Алетрис'
update Cards set ExpAtack=1,IsDefSpell=1 where Name='Мастер разума'
update Cards set ExpDef=1,IsDefShot=1 where Name='Горец'
update Cards set Armor=1 where Name='Старая гвардия'
update Cards set ExpDef=1 where Name='Хранитель Хартии'
update Cards set ExpAtack=1 where Name='Хигарт'
update Cards set IsDefPoison=1 where Name='Кнеллервирм'